# Site settings
title: Análise de Dados
email: dandara.sousa@ccc.ufcg.edu.br
description: > # this means to ignore newlines until "baseurl:"
  Um blog para expor as análises feitas da disciplina de Análise de Dados 1 2017.1 em Computação - UFCG.
url: "https://dandaramcsousa.github.io/AnaliseDeDados1/" # the base hostname & protocol for your site
twitter_username: d4ndara
github_username:  dandaramcsousa
permalink: /:year/:month/:title.html
baseurl: /AnaliseDeDados1

# Build settings
markdown: kramdown
